/*  File generated by StatWeave  */
display "--- Ou" "tput file from StatWeave, engine = StataEngine ---"


program define SWVrun
//-------


/* ---- Chunk 1: "stock_watson-1-Stata" ----- */
display "!-Stat" "Weave-!/swv~line 62~YFGPJ2/out"
set linesize 80
use ..\stata\hmda_sw.dta
gen deny = (s7==3)
gen pi_rat = s46/100
gen black = (s13==3)
display "@-Stat" "Weave-!/swv~line 62~YFGPJ2/out"

/* ---- Chunk 2: "stock_watson-2-Stata" ----- */
display "!-Stat" "Weave-!/swv~line 72~YFGPJ3/out"
summarize deny if (black==1)
display "@-Stat" "Weave-!/swv~line 72~YFGPJ3/out"

/* ---- Chunk 3: "stock_watson-3-Stata" ----- */
display "!-Stat" "Weave-!/swv~line 76~YFGPJ4/out"
summarize deny if (black==0)
display "@-Stat" "Weave-!/swv~line 76~YFGPJ4/out"

/* ---- Chunk 4: "stock_watson-4-Stata" ----- */
display "!-Stat" "Weave-!/swv~line 82~YFGPJ5/out"
gen hse_inc = s45/100
gen loan_val = s6/s50
gen ccred = s43
gen mcred = s42
gen pubrec = (s44>0)
gen denpmi = (s53==1)
gen selfemp = (s27a==1)
gen married = (s23a=="M")
gen single = (married==0)
gen hischl = (school>=12)
gen probunmp = uria
gen condo = (s51 == 1)
sum pi_rat hse_inc loan_val ccred mcred pubrec denpmi selfemp ///
 single hischl probunmp condo black deny
display "@-Stat" "Weave-!/swv~line 82~YFGPJ5/out"

/* ---- Chunk 5: "stock_watson-5-Stata" ----- */
display "!-Stat" "Weave-!/swv~line 101~YFGPJ6/out"
gen ltv_med = (loan_val>=0.80)*(loan_val<=.95)
gen ltv_high = (loan_val>0.95) 
gen blk_pi = black*pi_rat
gen blk_hse = black*hse_inc
gen ccred3 = (ccred==3) 
gen ccred4 = (ccred==4)
gen ccred5 = (ccred==5)
gen ccred6 = (ccred==6)
gen mcred3 = (mcred==3)
gen mcred4 = (mcred==4)
display "@-Stat" "Weave-!/swv~line 101~YFGPJ6/out"

/* ---- Chunk 6: "stock_watson-6-Stata" ----- */
display "!-Stat" "Weave-!/swv~line 118~YFGPJ7/out"
local controls pi_rat hse_inc ltv_med ltv_high ccred mcred ///
	pubrec denpmi selfemp
regress deny i.black `controls', robust
eststo LPM
display "@-Stat" "Weave-!/swv~line 118~YFGPJ7/out"

/* ---- Chunk 7: "stock_watson-7-Stata" ----- */
display "!-Stat" "Weave-!/swv~line 127~YFGPJ8/out"
logit deny i.black `controls', r
margins black, atmeans vsquish
quietly estadd margins black, atmeans
mat m = e(margins_b)
quietly estadd scalar prob_white = m[1,1]
quietly estadd scalar prob_black = m[1,2]
quietly estadd scalar prob_diff = m[1,2] - m[1,1]
eststo Logit_2
display "@-Stat" "Weave-!/swv~line 127~YFGPJ8/out"

/* ---- Chunk 8: "stock_watson-8-Stata" ----- */
display "!-Stat" "Weave-!/swv~line 142~YFGPJ9/out"
quietly probit deny i.black `controls', r
quietly estadd margins black, atmeans
mat m = e(margins_b)
quietly estadd scalar prob_white = m[1,1]
quietly estadd scalar prob_black = m[1,2]
quietly estadd scalar prob_diff = m[1,2] - m[1,1]
eststo Probit_3
display "@-Stat" "Weave-!/swv~line 142~YFGPJ9/out"

/* ---- Chunk 9: "stock_watson-9-Stata" ----- */
display "!-Stat" "Weave-!/swv~line 154~YFGPJ10/out"
quietly probit deny i.black `controls' single hischl probunmp, r
quietly estadd margins black, atmeans
mat m = e(margins_b)
quietly estadd scalar prob_white = m[1,1]
quietly estadd scalar prob_black = m[1,2]
quietly estadd scalar prob_diff = m[1,2] - m[1,1]
eststo Probit_4

quietly probit deny i.black `controls' single hischl probunmp ///
 mcred3 mcred4 ccred3 ccred4 ccred5 ccred6 condo, r
quietly estadd margins black, atmeans
mat m = e(margins_b)
quietly estadd scalar prob_white = m[1,1]
quietly estadd scalar prob_black = m[1,2]
quietly estadd scalar prob_diff = m[1,2] - m[1,1]
eststo Probit_5

quietly probit deny i.black `controls' ///
 single hischl probunmp i.black#c.pi_rat i.black#c.hse_inc
quietly estadd margins black, atmeans
mat m = e(margins_b)
quietly estadd scalar prob_white = m[1,1]
quietly estadd scalar prob_black = m[1,2]
quietly estadd scalar prob_diff = m[1,2] - m[1,1]
eststo Probit_inter
display "@-Stat" "Weave-!/swv~line 154~YFGPJ10/out"

/* ---- Chunk 10: "stock_watson-10-Stata" ----- */
display "!-Stat" "Weave-!/swv~line 184~YFGPJ11/out"
set linesize 120
esttab LPM Logit_2 Probit_3 Probit_4 Probit_5 Probit_inter, ///
	stats(prob_white prob_black prob_diff)  mtitle replace
display "@-Stat" "Weave-!/swv~line 184~YFGPJ11/out"

/* ---- Chunk 11: "stock_watson-11-Stata" ----- */
display "!-Stat" "Weave-!/swv~line 191~YFGPJ12/out"
quietly logit deny i.black `controls', r
quietly margins black, atmeans
quietly marginsplot
display "@-Stat" "Weave-!/swv~line 191~YFGPJ12/out"
graph display, xsize(6.0) ysize(4.0)
graph export stock_watson-11-Stata-fig.eps,  replace

//--------------
end

SWVrun
log using stata_check.smcl

